Update surface Hex package to v0.11.5
This was required to fix numerous compilation errors for `surface` files
in Elixir versions >= 1.16.x:

e.g.
```
==> surface
Compiling 145 files (.ex)
      warning: function require_expr/2 is unused
      │
 1029 │   defp require_expr(module, line) do
      │        ~
      │
      └─ lib/surface/compiler/eex_engine.ex:1029:8: Surface.Compiler.EExEngine (module)

warning: negative steps are not supported in String.slice/2, pass 1..-2//1 instead
Warning:   (elixir 1.16.3) lib/string.ex:2369: String.slice/2
  lib/surface/api.ex:618: anonymous fn/2 in Surface.API.generate_props_docs/1
  (elixir 1.16.3) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
  lib/surface/api.ex:616: Surface.API.generate_props_docs/1
  lib/surface/api.ex:599: Surface.API.do_generate_docs/2
  lib/surface/api.ex:70: Surface.API."MACRO-__before_compile__"/2

warning: negative steps are not supported in String.slice/2, pass 1..-2//1 instead
Warning:   (elixir 1.16.3) lib/string.ex:2369: String.slice/2
  lib/surface/api.ex:618: anonymous fn/2 in Surface.API.generate_props_docs/1
  (elixir 1.16.3) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
  lib/surface/api.ex:616: Surface.API.generate_props_docs/1
  lib/surface/api.ex:599: Surface.API.do_generate_docs/2
  lib/surface/api.ex:70: Surface.API."MACRO-__before_compile__"/2
```

```
Resolving Hex dependencies...                                                                                                           Resolution completed in 0.062s
New:                                                                                                                                      castore 1.0.8
  phoenix_template 1.0.4                                                                                                                  websock 0.5.3                                                                                                                           websock_adapter 0.5.7                                                                                                                 Unchanged:
  earmark_parser 1.4.26
  ex_doc 0.28.5
  floki 0.33.1
  html_entities 0.5.2
  makeup 1.1.0
  makeup_elixir 0.16.0
  makeup_erlang 0.1.1
  nimble_parsec 1.2.3
Upgraded:
  mime 2.0.3 => 2.0.6
  phoenix 1.6.12 => 1.7.14
  phoenix_html 3.2.0 => 3.3.4
  phoenix_live_view 0.17.11 => 0.20.12 (minor)
  phoenix_pubsub 2.1.1 => 2.1.3
  plug 1.13.6 => 1.16.1
  plug_crypto 1.2.3 => 2.1.0 (major)
  sourceror 0.11.2 => 1.0.3 (major)
  surface 0.8.4 => 0.11.5 (minor)
  telemetry 1.1.0 => 1.3.0
* Updating phoenix_html (Hex package)
* Updating phoenix_live_view (Hex package)
* Updating surface (Hex package)
* Updating sourceror (Hex package)
* Updating phoenix (Hex package)
* Updating plug (Hex package)
* Updating telemetry (Hex package)
* Updating mime (Hex package)
* Updating plug_crypto (Hex package)
* Updating phoenix_pubsub (Hex package)
```